### ISSUE TITLE
149 max devices supported issue

### ISSUE THREAD

**Issue by stvnjnk** [ilcato/homebridge-fibaro-home-center#130]
Hi,

I tried adding my HC3 to homebridge via the plugin but I get the error that only 149 devices are supported as it is the homekit limit. I have 117 physical devices paired to my HC3 but I guess it counts the virtual ones too as one fibaro double switch has 4 sub-devices that appear on HC3. Is there any way to remove the limit and choose which devices to keep or not? Thanks for the help

**Comment by ilcato** [comment]
@stvnjnk name the device in HC starting with _
It will not included into HomeKit.

**Comment by stvnjnk** [comment]
Done and the error has gone away but I get this now:

Error getting data from Home Center:  TypeError: Cannot read properties of undefined (reading 'name')
    at /homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:159:59
    at Array.map (<anonymous>)
    at FibaroHC.LoadAccessories (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:154:13)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:132:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
