### ISSUE TITLE
After adding Yubii home I get the following error. "Error: Not Implemented" - logs attached

### ISSUE THREAD

**Issue by dsylex** [ilcato/homebridge-fibaro-home-center#133]
Hey, @ilcato  

so I've added Yubii home via the HB plugin but I get the following error spam. 
Any idea how to solve this?

P.S. I'm using elero roller shutters

Much appreciated!

```
[13/03/2023, 23:02:44] [FibaroHC] Restarting Process...
[13/03/2023, 23:02:45] [FibaroHC] Launched child bridge with PID XXXXXX
[13/03/2023, 23:02:46] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[13/03/2023, 23:02:46] [FibaroHC] Loaded homebridge-fibaro-home-center v1.2.15 child bridge successfully
[13/03/2023, 23:02:46] Loaded 1 cached accessories from cachedAccessories.XXXXXXXXX.
[13/03/2023, 23:02:46] [FibaroHC] Loading accessory from cache: Office Blinds
[13/03/2023, 23:02:46] Homebridge v1.6.0 (HAP v0.11.0) (FibaroHC) is running on port 50870.
[13/03/2023, 23:02:46] [FibaroHC] Error getting data from Home Center:  Error: Not Implemented
    at Request.callback (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:900:17)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1153:18)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  status: 501,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 501,
      statusMessage: 'Not Implemented',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      text: '',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'GET',
      url: 'https://yh-XXXXXXXX.local//api/settings/info',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      _lookup: undefined,
      throttle: [Throttle],
      serial: false,
      _maskedEnd: [Function (anonymous)],
      end: [Function (anonymous)],
      _ca: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 47 7a 44 43 43 42 4c 53 67 41 77 49 42 41 67 49 42 41 54 ... 2369 more bytes>,
      _maskedCallback: [Function (anonymous)],
      req: [ClientRequest],
      protocol: 'https:',
      host: 'yh-XXXXXXXX.local',
      _endCalled: true,
      _callback: [Function: cleanup],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET //api/settings/info HTTP/1.1\r\n' +
        'Host: yh-XXXXXXXX.local\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Authorization: Basic YWRtaW46YWRtaW4=\r\n' +
        'accept: json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '//api/settings/info',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'yh-XXXXXXXX.local',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    text: '',
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx',
      date: 'Mon, 13 Mar 2023 22:02:46 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    header: {
      server: 'nginx',
      date: 'Mon, 13 Mar 2023 22:02:46 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    statusCode: 501,
    status: 501,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot GET //api/settings/info (501)
        at Response.toError (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:110:17)
        at Response._setStatusProperties (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/response-base.js:107:48)
        at new Response (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:41:8)
        at Request._emitResponse (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:951:20)
        at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1153:38)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
      status: 501,
      text: '',
      method: 'GET',
      path: '//api/settings/info'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: '',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}

/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:900
        error = new Error(message);
                ^
Error: Not Implemented
    at Request.callback (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:900:17)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1153:18)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[13/03/2023, 23:02:46] [FibaroHC] Child bridge process ended
[13/03/2023, 23:02:46] [FibaroHC] Process Ended. Code: 1, Signal: null
```

**Comment by dsylex** [comment]
I don't think it's the Elero blind causing the issue as I can't even add the Yubii Home Center to Homebridge but I've pasted the 'GET Devices' answer below.

Thanks for your help in advance @ilcato 

```
[
  {
    "id": 1,
    "name": "zwave",
    "roomID": 219,
    "view": [],
    "type": "com.fibaro.zwavePrimaryController",
    "baseType": "",
    "enabled": true,
    "visible": false,
    "isPlugin": false,
    "parentId": 0,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [
      "zwave"
    ],
    "properties": {
      "UIMessageSendTime": 0,
      "autoConfig": 0,
      "configured": true,
      "date": "a",
      "dead": false,
      "deviceControlType": 1,
      "deviceIcon": 28,
      "deviceRole": "Other",
      "disabled": 1,
      "emailNotificationID": 0,
      "emailNotificationType": 0,
      "endPoint": 0,
      "endPointId": 0,
      "liliOffCommand": "",
      "liliOnCommand": "",
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": true,
      "model": "",
      "nodeID": 1,
      "nodeId": 1,
      "parameters": [],
      "parametersTemplate": 0,
      "pollingDeadDevice": false,
      "pollingTime": 1354829138,
      "pollingTimeNext": 1354837724,
      "pollingTimeSec": 125,
      "productInfo": "",
      "pushNotificationID": 0,
      "pushNotificationType": 0,
      "remoteGatewayId": 0,
      "requestNodeNeighborStat": 0,
      "requestNodeNeighborStatTimeStemp": "",
      "requestNodeNeighborState": "",
      "requestNodeNeighborStateTimeStemp": "",
      "saveLogs": true,
      "serialNumber": "",
      "showChildren": 1,
      "smsNotificationID": 0,
      "smsNotificationType": 0,
      "status": "STAT_IDLE",
      "sunriseHour": "06:00",
      "sunsetHour": "17:47",
      "useTemplate": true,
      "userDescription": "",
      "value": 0,
      "zwaveBuildVersion": "3.67",
      "zwaveCompany": "Unknown",
      "zwaveInfo": "",
      "zwaveRegion": "EU",
      "zwaveVersion": "4.33"
    },
    "actions": {
      "pollingDeadDevice": 1,
      "pollingTimeSec": 1,
      "reconfigure": 0,
      "requestNodeNeighborUpdate": 1,
      "turnOff": 0,
      "turnOn": 0
    },
    "created": 1678734055,
    "modified": 1678734130,
    "sortOrder": 1
  },
  {
    "id": 2,
    "name": "admin",
    "roomID": 219,
    "view": [],
    "type": "HC_user",
    "baseType": "com.fibaro.voipUser",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 0,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [
      "voip"
    ],
    "properties": {
      "Email": "XXXXXXXXXXXXXXXXXX",
      "HotelModeRoom": 0,
      "LastPwdChange": 1678710273,
      "Latitude": XXXXXXXXXXXX,
      "Location": "XXXXXXXXXXXXXXXXX",
      "LocationTime": "2012-12-06 12:15",
      "LocationTimestamp": 1354792521,
      "Longitude": XXXXXXXXXXXXXXXX,
      "PreviousLatitude": XXXXXXXXXXXXXXXX,
      "PreviousLocation": "XXXXXXXXXXXXXXXX",
      "PreviousLocationTime": "2012-12-06 12:14",
      "PreviousLocationTimestamp": 1354792461,
      "PreviousLongitude": XXXXXXXXXXXXXXXX,
      "SendNotifications": true,
      "TrackUser": 0,
      "UserType": "superuser",
      "atHome": false,
      "deviceIcon": 91,
      "fidLastSynchronizationTimestamp": 1678734135,
      "fidRole": "USER",
      "fidUuid": "XXXXXXXXXXXXXXXX",
      "firmwareUpdateLevel": 0,
      "integrationPin": "",
      "saveLogs": true,
      "sipDisplayName": "_",
      "sipUserEnabled": true,
      "sipUserID": "1",
      "sipUserPassword": "",
      "skin": "light",
      "skinSetting": "manual",
      "useIntegrationPin": false,
      "useOptionalArmPin": false,
      "usePin": false
    },
    "actions": {
      "sendDefinedEmailNotification": 1,
      "sendDefinedSMSNotification": 2,
      "sendEmail": 2,
      "sendGlobalEmailNotifications": 1,
      "sendGlobalPushNotifications": 1,
      "sendGlobalSMSNotifications": 1,
      "sendPush": 1,
      "setSipDisplayName": 1,
      "setSipUserID": 1,
      "setSipUserPassword": 1
    },
    "created": 1678734055,
    "modified": 1678734123,
    "sortOrder": 2
  },
  {
    "id": 3,
    "name": "YR Weather",
    "roomID": 219,
    "view": [
      {
        "type": "json"
      }
    ],
    "type": "com.fibaro.yrWeather",
    "baseType": "com.fibaro.weather",
    "enabled": true,
    "visible": true,
    "isPlugin": true,
    "parentId": 0,
    "viewXml": true,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [],
    "properties": {
      "ConditionCode": 30,
      "ConditionCodeConverted": 0,
      "Humidity": 50.8,
      "Pressure": 1005.4,
      "Temperature": 12.1,
      "WeatherCondition": "partlyCloudy",
      "Wind": 24.48,
      "categories": [
        "other"
      ],
      "dead": false,
      "deadReason": "",
      "deviceControlType": 1,
      "deviceIcon": 158,
      "deviceRole": "Other",
      "emailNotificationID": 0,
      "emailNotificationType": 0,
      "hidden": false,
      "icon": {
        "path": "/plugins/com.fibaro.yrWeather/img/icon.png",
        "source": "HC"
      },
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "model": "",
      "pushNotificationID": 0,
      "pushNotificationType": 0,
      "remoteGatewayId": 0,
      "saveLogs": true,
      "smsNotificationID": 0,
      "smsNotificationType": 0,
      "supportedDeviceRoles": [
        "Other"
      ],
      "ui.config.hidden.caption": "This device is hidden in the system.",
      "ui.config.hidden.enabled": true,
      "ui.config.section1.caption": "Configuration",
      "ui.config.section1.enabled": true,
      "userDescription": "",
      "yrSymbolCode": "partlycloudy"
    },
    "actions": {},
    "created": 1678734055,
    "modified": 1678734123,
    "sortOrder": 3
  },
  {
    "id": 7,
    "name": "Nice Engine",
    "roomID": 0,
    "view": [],
    "type": "com.fibaro.niceEngine",
    "baseType": "",
    "enabled": true,
    "visible": false,
    "isPlugin": false,
    "parentId": 0,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [],
    "properties": {
      "icon": {}
    },
    "actions": {},
    "created": 1678734055,
    "modified": 1678734123,
    "sortOrder": 4
  },
  {
    "id": 20,
    "name": "iPhone",
    "roomID": 0,
    "view": [],
    "type": "iOS_device",
    "baseType": "",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 0,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [],
    "properties": {
      "DeviceToken": "XXXXXXXXXXXXXXXX",
      "DeviceUID": "XXXXXXXXXXXXXXXX",
      "Push": true,
      "deviceIcon": 91,
      "lastLoggedUser": 2
    },
    "actions": {
      "sendDefinedPushNotification": 1,
      "sendPush": 1
    },
    "created": 1678734220,
    "modified": 1678747400,
    "sortOrder": 5
  },
  {
    "id": 35,
    "name": "RevoLine",
    "roomID": 219,
    "view": [],
    "type": "com.fibaro.device",
    "baseType": "",
    "enabled": true,
    "visible": false,
    "isPlugin": false,
    "parentId": 7,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [
      "elero",
      "eleroBidi"
    ],
    "properties": {
      "categories": [
        "other"
      ],
      "configuration": true,
      "dead": false,
      "deadReason": "",
      "deviceControlType": 1,
      "deviceIcon": 28,
      "deviceRole": "Other",
      "deviceState": "Configured",
      "icon": {},
      "log": "",
      "logTemp": "",
      "macAddress": XXXXXXXXXXXXXXXX
      "manufacturer": "ELERO",
      "markAsDead": true,
      "model": "RevoLine",
      "niceId": 1,
      "niceProtocol": "EleroBidiPln2",
      "saveLogs": true,
      "supportedDeviceRoles": [
        "BlindsWithoutPositioning",
        "Awning"
      ],
      "userDescription": ""
    },
    "actions": {},
    "created": 1678736914,
    "modified": 1678736914,
    "sortOrder": 20
  },
  {
    "id": 36,
    "name": "Office Blinds",
    "roomID": 224,
    "view": [
      {
        "assetsPath": "dynamic-plugins/com.fibaro.baseShutter",
        "name": "com.fibaro.baseShutter",
        "translatesPath": "/assets/i18n/com.fibaro.baseShutter",
        "type": "ts"
      },
      {
        "assetsPath": "dynamic-plugins/favorite-positions",
        "name": "favorite-positions",
        "translatesPath": "/assets/i18n/favorite-positions",
        "type": "ts"
      }
    ],
    "type": "com.fibaro.baseShutter",
    "baseType": "com.fibaro.actor",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 35,
    "viewXml": false,
    "hasUIView": true,
    "configXml": false,
    "interfaces": [
      "elero",
      "eleroBidi",
      "favoritePosition",
      "notification"
    ],
    "properties": {
      "categories": [
        "blinds"
      ],
      "configuration": true,
      "dead": false,
      "deadReason": "",
      "deviceControlType": 53,
      "deviceIcon": 228,
      "deviceRole": "BlindsWithoutPositioning",
      "deviceState": "Configured",
      "favoritePositions": [
        {
          "label": "Favorite position 1",
          "name": "FavoritePosition1",
          "value": 50
        },
        {
          "label": "Favorite position 2",
          "name": "FavoritePosition2",
          "value": 50
        }
      ],
      "favoritePositionsNativeSupport": true,
      "icon": {
        "path": "/assets/icon/fibaro/blind/blindOpened.png",
        "source": "HC"
      },
      "log": "",
      "logTemp": "",
      "macAddress": 10970160,
      "manufacturer": "ELERO",
      "markAsDead": true,
      "model": "RevoLine",
      "niceId": 1,
      "niceProtocol": "EleroBidiPln2",
      "saveLogs": true,
      "state": "Opened",
      "supportedDeviceRoles": [
        "BlindsWithoutPositioning",
        "Awning"
      ],
      "supportedNotifications": {
        "1": {
          "eventValues": {
            "1": {
              "key": "ETX_ALERT_OVERTEMPERATURE",
              "saveToPanel": true
            },
            "2": {
              "key": "ETX_ALERT_BLOCKED",
              "saveToPanel": true
            }
          },
          "key": "ETX_ALERT"
        }
      },
      "userDescription": ""
    },
    "actions": {
      "close": 0,
      "open": 0,
      "setFavoritePosition": 1,
      "stop": 0
    },
    "created": 1678736914,
    "modified": 1678736958,
    "sortOrder": 21
  }
]
```

**Comment by dsylex** [comment]
it works if I use the IP address instead of yh-XXXXXXXX.local address
