### ISSUE TITLE
Update 1.2.17 crashes homebridge

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#139]
Hello ilcato,

Your latest update, on my configuration, will make homebridge crash. Reverting to older version make it work again. Here the error

06/04/2023, 21:31:31] [FibaroHC] Error getting data from Home Center:  TypeError: Cannot read properties of undefined (reading 'deviceControlType')
    at new FibaroAccessory (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:46:57)
    at FibaroHC.addAccessory (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:238:7)
    at FibaroHC.LoadAccessories (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:205:12)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:155:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/04/2023, 21:31:31] TypeError: Cannot read properties of undefined (reading 'deviceControlType')
    at new FibaroAccessory (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:46:57)
    at FibaroHC.addAccessory (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:238:7)
    at FibaroHC.LoadAccessories (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:205:12)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:155:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ilcato** [comment]
on it

**Comment by ilcato** [comment]
Fixed in 1.2.18

**Comment by redeemer666** [comment]
I confirm it's working now. 

Thanks a lot!
