### ISSUE TITLE
Error after update to 1.2.19

### ISSUE THREAD

**Issue by mkz212** [ilcato/homebridge-fibaro-home-center#143]
```
Error fetching updates:  Error: Response timeout of 10000ms exceeded
    at Request._timeoutError (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/request-base.js:771:17)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/request-base.js:794:12)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  timeout: 10000,
  code: 'ECONNABORTED',
  errno: 'ETIMEDOUT',
  response: undefined
}
```

**Comment by mkz212** [comment]
There is no error in 1.2.18

**Comment by ilcato** [comment]
@mkz212, reverted. please use 1.2.20

**Comment by mkz212** [comment]
Ok. For some time now, the device has been showing me no response from time to time. Does your update have anything to do with it?

P.S.: In the meantime, please take a look #142

**Comment by mkz212** [comment]
The worst thing is that when this happens there is nothing strange in the logs in homebridge. All devices , not only from Fibaro plugin , but also from AC, Dummy Switch etc. are "no response". Only devices that are unbridged are ok.
