### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Krillle** [ilcato/homebridge-fibaro-home-center#153]
The plugin makes my homebridge crashing frequently: 

```
[04/11/2023, 13:51:59] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:111:36)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:20
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Konfiguration:**
Homebridge v1.7.0
homebridge-fibaro-home-center v1.2.20
Node.js v18.16.0
Raspbian GNU/Linux Bullseye (11)
Fresh Install on Raspberry Pi 3+
Home Center 2 v4.630

**Logfile excerpt:**
```
[04/11/2023, 13:56:18] [FibaroHC] Updating value for device:  131  parameter: Temperature Display Units
[04/11/2023, 13:56:18] [FibaroHC] Updating value for device:  131  parameter: Current Temperature
[04/11/2023, 13:56:18] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:111:36)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:20
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[04/11/2023, 13:56:18] Got SIGTERM, shutting down Homebridge...
[04/11/2023, 13:56:18] [iRobot] Disconnecting From Roomba: Roomba
[04/11/2023, 13:56:18] [iRobot] Roomba Roomba connection closed
[04/11/2023, 13:56:23] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[04/11/2023, 13:56:28] [HB Supervisor] Restarting Homebridge...
```

**Comment by mkz212** [comment]
@Krillle can you try latest version? v 1.4.0

**Comment by Krillle** [comment]
@mkz212  v1.4.0 is installed. I will monitor and report. Thank you for taking care.

**Comment by Krillle** [comment]
@mkz212  unfortunately same issue with v1.4.0.
It always happens after Device 131, which is a heating zone. 

```
[10/11/2023, 19:26:54] [FibaroHC] Temperatur 137.0.1 [139]: 25.5 C
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:59] [FibaroHC] Wohnbereich [131]: 23.0 C
[10/11/2023, 19:27:59] [FibaroHC] Wohnbereich [131]: 0 %
[10/11/2023, 19:27:59] [FibaroHC] Temperatur 129.0.1 [131]: 23.5 C
[10/11/2023, 19:27:59] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:110:36)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:20
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/11/2023, 19:27:59] Got SIGTERM, shutting down Homebridge...
```

**Comment by mkz212** [comment]
I will try to check it out. If you can, provide more data - for which device is this happening? Or spontaneously or during starting / turning off the device? How often? Maybe also put here API  response for this device? (You will get the API by entering in browser:  IP/api/device where IP is your Home Center IP. (text, no screenshot)

**Comment by Krillle** [comment]
It seems to happen spontaneously, but not always always on device 131, which is a heating zone. 

`http://HC2.local/api/devices/131` reports:

```
{
  "id": 131,
  "name": "Temperatur 129.0.1",
  "roomID": 4,
  "type": "com.fibaro.temperatureSensor",
  "baseType": "com.fibaro.multilevelSensor",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 129,
  "remoteGatewayId": 0,
  "interfaces": [
    "zwave"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 2,
        "value": 1
      },
      {
        "id": 2,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 2,
        "value": 1
      },
      {
        "id": 3,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 4,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 2,
        "value": 3
      },
      {
        "id": 5,
        "lastReportedValue": 50,
        "lastSetValue": 50,
        "size": 2,
        "value": 50
      },
      {
        "id": 6,
        "lastReportedValue": 400,
        "lastSetValue": 400,
        "size": 2,
        "value": 400
      },
      {
        "id": 7,
        "lastReportedValue": 50,
        "lastSetValue": 50,
        "size": 2,
        "value": 50
      },
      {
        "id": 8,
        "lastReportedValue": 400,
        "lastSetValue": 400,
        "size": 2,
        "value": 400
      },
      {
        "id": 9,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 10,
        "lastReportedValue": 240,
        "lastSetValue": 240,
        "size": 2,
        "value": 240
      },
      {
        "id": 11,
        "lastReportedValue": 240,
        "lastSetValue": 240,
        "size": 2,
        "value": 240
      },
      {
        "id": 12,
        "lastReportedValue": 2,
        "lastSetValue": 2,
        "size": 2,
        "value": 2
      },
      {
        "id": 13,
        "lastReportedValue": 210,
        "lastSetValue": 210,
        "size": 2,
        "value": 210
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Heatit",
    "zwaveInfo": "6,3,83",
    "zwaveVersion": "1.5",
    "categories": "[\"climate\"]",
    "configured": true,
    "dead": "false",
    "deadReason": "",
    "deviceControlType": "0",
    "deviceIcon": "1004",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": "true",
    "model": "",
    "nodeId": "32",
    "offset": "0.00",
    "parametersTemplate": "720",
    "productInfo": "1,155,0,1,0,1,1,5",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'00000001",
    "showFireAlarm": "true",
    "showFreezeAlarm": "false",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "unit": "C",
    "useTemplate": "true",
    "userDescription": "",
    "value": "23.10"
  },
  "actions": {
    "reconfigure": 0
  },
  "created": 1698659718,
  "modified": 1698659718,
  "sortOrder": 174
}

```

**Comment by mkz212** [comment]
I don't think it's this device (id 131) that causes the problem. It's rather one of: Climate Zone or Heating Zone? Do you have something like that? If so, can you paste the API response for them?

**Comment by mkz212** [comment]
Also, paste the current error here (from version 1.4.0) please.

**Comment by Krillle** [comment]
The problem seems to be related to Heating Zones indeed.

The log file reports `[FibaroHC] Wohnbereich [131]: 23.0 C`. "Wohnbereich" is a Heating Zone
The actual device 131 is the temperature sensor of a heating thermostat in a room in that heating zone.
We habe an edge case: Other than the rest of the heating zones, this zone has only one thermostat. 

This is the error with v1.4.0:

```
[10/11/2023, 19:26:54] [FibaroHC] Temperatur 137.0.1 [139]: 25.5 C
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:06] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:07] [FibaroHC] power is not a number. 
[10/11/2023, 19:27:59] [FibaroHC] Wohnbereich [131]: 23.0 C
[10/11/2023, 19:27:59] [FibaroHC] Wohnbereich [131]: 0 %
[10/11/2023, 19:27:59] [FibaroHC] Temperatur 129.0.1 [131]: 23.5 C
[10/11/2023, 19:27:59] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:110:36)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:20
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/11/2023, 19:27:59] Got SIGTERM, shutting down Homebridge...
```

**Comment by mkz212** [comment]
@Krillle please try next update (not version 1.4.0 but version above ). If this still does not fix the problem, write.

**Comment by Krillle** [comment]
@mkz212 still same issue with v1.4.1:

```
[12/11/2023, 11:43:24] [FibaroHC] Wohnbereich [131]: 23.0 C
[12/11/2023, 11:43:24] [FibaroHC] Wohnbereich [131]: 0 
[12/11/2023, 11:43:24] [FibaroHC] Temperatur 129.0.1 [131]: 24.4 C
[12/11/2023, 11:43:25] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:110:34)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:18
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/11/2023, 11:43:25] Got SIGTERM, shutting down Homebridge...
```

**Device 131 API response:**
```
{
  "id": 131,
  "name": "Temperatur 129.0.1",
  "roomID": 4,
  "type": "com.fibaro.temperatureSensor",
  "baseType": "com.fibaro.multilevelSensor",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 129,
  "remoteGatewayId": 0,
  "interfaces": [
    "zwave"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 2,
        "value": 1
      },
      {
        "id": 2,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 2,
        "value": 1
      },
      {
        "id": 3,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 4,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 2,
        "value": 3
      },
      {
        "id": 5,
        "lastReportedValue": 50,
        "lastSetValue": 50,
        "size": 2,
        "value": 50
      },
      {
        "id": 6,
        "lastReportedValue": 400,
        "lastSetValue": 400,
        "size": 2,
        "value": 400
      },
      {
        "id": 7,
        "lastReportedValue": 50,
        "lastSetValue": 50,
        "size": 2,
        "value": 50
      },
      {
        "id": 8,
        "lastReportedValue": 400,
        "lastSetValue": 400,
        "size": 2,
        "value": 400
      },
      {
        "id": 9,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 10,
        "lastReportedValue": 240,
        "lastSetValue": 240,
        "size": 2,
        "value": 240
      },
      {
        "id": 11,
        "lastReportedValue": 240,
        "lastSetValue": 240,
        "size": 2,
        "value": 240
      },
      {
        "id": 12,
        "lastReportedValue": 2,
        "lastSetValue": 2,
        "size": 2,
        "value": 2
      },
      {
        "id": 13,
        "lastReportedValue": 210,
        "lastSetValue": 210,
        "size": 2,
        "value": 210
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Heatit",
    "zwaveInfo": "6,3,83",
    "zwaveVersion": "1.5",
    "categories": "[\"climate\"]",
    "configured": true,
    "dead": "false",
    "deadReason": "",
    "deviceControlType": "0",
    "deviceIcon": "1004",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": "true",
    "model": "",
    "nodeId": "32",
    "offset": "0.00",
    "parametersTemplate": "720",
    "productInfo": "1,155,0,1,0,1,1,5",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'00000001",
    "showFireAlarm": "true",
    "showFreezeAlarm": "false",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "unit": "C",
    "useTemplate": "true",
    "userDescription": "",
    "value": "24.50"
  },
  "actions": {
    "reconfigure": 0
  },
  "created": 1698659718,
  "modified": 1698659718,
  "sortOrder": 174
}
```

**Full log:**
```
[12/11/2023, 11:43:35] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[12/11/2023, 11:43:35] [HB Supervisor] Started Homebridge v1.7.0 with PID: 26851
[12/11/2023, 11:43:37] Loaded config.json with 2 accessories and 4 platforms.
[12/11/2023, 11:43:37] Loaded 85 cached accessories from cachedAccessories.
[12/11/2023, 11:43:38] ---
[12/11/2023, 11:43:38] Loaded plugin: homebridge-dummy@0.9.0
[12/11/2023, 11:43:38] Registering accessory 'homebridge-dummy.DummySwitch'
[12/11/2023, 11:43:38] ---
[12/11/2023, 11:43:39] Loaded plugin: homebridge-dyson-pure-cool@2.7.6
[12/11/2023, 11:43:39] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/11/2023, 11:43:39] ---
[12/11/2023, 11:43:39] Loaded plugin: homebridge-fibaro-home-center@1.4.1
[12/11/2023, 11:43:39] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[12/11/2023, 11:43:39] ---
[12/11/2023, 11:43:40] Loaded plugin: homebridge-http-switch@0.5.36
[12/11/2023, 11:43:40] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[12/11/2023, 11:43:40] ---
[12/11/2023, 11:43:41] Loaded plugin: homebridge-irobot@2.1.16
[12/11/2023, 11:43:41] Registering platform 'homebridge-irobot.iRobotPlatform'
[12/11/2023, 11:43:41] ---
[12/11/2023, 11:43:41] Loading 4 platforms...
[12/11/2023, 11:43:41] [FibaroHC] Initializing FibaroHC platform...
[12/11/2023, 11:43:41] [iRobot] Initializing iRobotPlatform platform...
[12/11/2023, 11:43:41] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
[12/11/2023, 11:43:41] Loading 2 accessories...
[12/11/2023, 11:43:41] [Alle weg] Initializing DummySwitch accessory...
[12/11/2023, 11:43:42] [Garagentor] Initializing HTTP-SWITCH accessory...
[12/11/2023, 11:43:42] [Garagentor] Switch successfully configured...
[12/11/2023, 11:43:42] [iRobot] Loading accessory from cache: Roomba
[12/11/2023, 11:43:42] [iRobot] Logging into iRobot...
[12/11/2023, 11:43:45] [iRobot] Configuring roomba: Roomba
[12/11/2023, 11:43:46] [iRobot] Restoring existing accessory from cache: Roomba
[12/11/2023, 11:43:47] [DysonPureCoolPlatform] Device with serial number NN2-EU-KKxxxxA: product type 475
[12/11/2023, 11:43:47] [DysonPureCoolPlatform] Device with serial number VS9-EU-KFxxxxA: product type 438
[12/11/2023, 11:43:47] [DysonPureCoolPlatform] Accessories initialized.
Setup Payload:
X-HM://002xxxxxxxW6T
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
[12/11/2023, 11:43:48] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge) is running on port 51194.
[12/11/2023, 11:43:48] [iRobot] Succefully connected to roomba Roomba
[12/11/2023, 11:43:49] [FibaroHC] Loading accessories
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:44:01] [FibaroHC] power is not a number. 
[12/11/2023, 11:46:23] [FibaroHC] Temperatur 44.0.1 [46]: 24.6 C
[12/11/2023, 11:46:33] [FibaroHC] Temperatur 133.0.1 [135]: 29.2 C
[12/11/2023, 11:47:40] [FibaroHC] Wohnbereich [131]: 23.0 C
[12/11/2023, 11:47:40] [FibaroHC] Wohnbereich [131]: 0 
[12/11/2023, 11:47:40] [FibaroHC] Temperatur 129.0.1 [131]: 24.5 C
[12/11/2023, 11:47:40] TypeError: Cannot read properties of undefined (reading '0')
    at GetFunctions.getCurrentTemperature (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:197:85)
    at Poller.manageValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:110:34)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:49:18
    at Array.map (<anonymous>)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:47:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/11/2023, 11:47:40] Got SIGTERM, shutting down Homebridge...
```
