### ISSUE TITLE
Loading accessories failing

### ISSUE THREAD

**Issue by termoose** [ilcato/homebridge-fibaro-home-center#188]
I'm seeing the following error message:

```bash
[12/9/2023, 5:21:06 AM] [FibaroHC] Loading accessories
[12/9/2023, 5:21:06 AM] [FibaroHC] Error getting data from Home Center:  TypeError: Cannot read properties of undefined (reading 'name')
    at /homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:187:59
    at Array.map (<anonymous>)
    at FibaroHC.LoadAccessories (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:182:13)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:158:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:182
    devices.map((s, i, a) => {
            ^
TypeError: Cannot read properties of undefined (reading 'name')
    at /homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:187:59
    at Array.map (<anonymous>)
    at FibaroHC.LoadAccessories (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:182:13)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:158:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I tried getting the response from the `/api/devices` myself using CURL, and I see JSON objects with `name` keys in them. 

My config is just using the `host` instead of the `url` here, but the same issue happens if I use a `http` host. I'm not able to use `https` for complicated reason (mDNS in TrueNas' kubernetes pod setup), but I guess that shouldn't be required?

```json
        {
            "name": "FibaroHC",
            "url_": "https://hc3l-00000686.local",
            "host": "192.168.1.132",
            "username": "XX",
            "password": "XX",
            "pollerperiod": 2,
            "securitysystem": "disabled",
            "addRoomNameToDeviceName": "enabled",
            "logsLevel": 1,
            "advControl": 0,
            "_bridge": {
                "username": "0E:AE:34:D9:5D:B0",
                "port": 43277
            },
            "platform": "FibaroHC"
        }
```

Edit: should mention that I'm running Home Center 3 Lite, and I'm on version `5.150.18`.
Edit2: ended up debugging this some more, and I see the code causing the issue is only running if `addRoomNameToDeviceName` is set  to `enabled`. If I disable this I don't get the error message, but might be a bug with this functionality?

**Comment by ilcato** [comment]
@termoose, can you test if homebridge-fibaro-home-center@1.5.2-beta.12 solves this issue? Thanks

**Comment by ilcato** [comment]
The fix is on latest
