### ISSUE TITLE
Error fetching updates

### ISSUE THREAD

**Issue by KJTamas** [ilcato/homebridge-fibaro-home-center#269]
Hi ,
After ugraded to 1.7.1 i got an error:

Error fetching updates:  TypeError: Cannot read properties of null (reading 'getCharacteristic')
    at GetFunctions.getBrightness (/homebridge/node_modules/homebridge-fibaro-home-center/src/getFunctions.ts:130:38)
    at Poller.manageGlobalVariableDevice (/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:174:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Poller.poll (/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:64:7)
[1/14/2024, 3:31:07 PM] [XxxxxxXX] Next try in 1 minute

I got this every minutes. 
Can you help me, what is this?

Br,
Tamas

**Comment by ilcato** [comment]
@KJTamas try version v1.7.2-beta.1

**Comment by KJTamas** [comment]
This was the solution. Thx.

**Comment by ilcato** [comment]
ok, closing
