### ISSUE TITLE
Gate from HC3L not visible in homebridge

### ISSUE THREAD

**Issue by stekki007** [ilcato/homebridge-fibaro-home-center#282]
As the title mentions, I just installed a HC3Lite and coupled it to homebridge.  My wall plug is visible in homebridge, but my Nice gate is not.

I am using the IBT4ZWAVE dongle in my gate controller from Nice, everything works in HC3Lite.  
My firmware is 5.150.18.

Any help is appreciated :)

**Comment by mkz212** [comment]
Open in browser: http://FIBARO-IP/api/devices/DEVICE-ID (replace FIBARO-IP with your Home Center IP and DEVICE-ID with device ID) and login.

paste here response

**Comment by stekki007** [comment]
{"id":26,"name":"Gate","roomID":219,"view":[{"assetsPath":"dynamic-plugins/com.fibaro.baseShutter","name":"com.fibaro.baseShutter","translatesPath":"/assets/i18n/com.fibaro.baseShutter","type":"ts"}],"type":"com.fibaro.baseShutter","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":25,"viewXml":false,"hasUIView":true,"configXml":false,"interfaces":["accessControlForceExceededEvent","accessControlObstacleEvent","identifiable","notification","parameters","stepByStep","systemHadwareFailureEvent","zwave","zwaveIndicator","zwaveProtection"],"properties":{"parameters":[],"pollingTimeSec":0,"zwaveCompany":"Nice S.p.A.","zwaveInfo":"3,7,13","zwaveVersion":"7.0","RFProtectionState":0,"RFProtectionSupport":3,"categories":["gates"],"configured":true,"dead":false,"deadReason":"","deviceControlType":63,"deviceIcon":199,"deviceRole":"GateDoubleLeaf","endPointId":0,"icon":{"path":"/assets/icon/fibaro/gate_doubleLeaf/gate_doubleLeafClosed.png","source":"HC"},"indicatorSupportedProperties":[],"indicatorValue":[],"localProtectionState":0,"localProtectionSupport":5,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"model":"","nodeId":8,"parameterProvider":"zwave","parametersTemplate":"875","productInfo":"4,65,36,0,16,0,7,0","protectionExclusiveControl":0,"protectionExclusiveControlSupport":false,"protectionState":0,"protectionTimeout":0,"protectionTimeoutSupport":false,"saveLogs":true,"serialNumber":"","state":"Closed","supportedDeviceRoles":["GarageDoorSectional","GarageDoorSwing","GarageDoorTilt","GateDoubleLeaf","GateSingleLeaf","GateSliding","Barrier","BlindsWithoutPositioning","BlindsWithPositioning","VenetianBlinds","Awning","Curtain","LamellarCurtain"],"supportedNotifications":{"6":{"eventValues":{"65":{"key":"blockScenes.notification.properties.6.65","saveToPanel":false}},"key":"blockScenes.notification.properties.6","stateValues":{"barrier-control-status":{"key":"blockScenes.notification.properties.barrier-control-status","values":{"0":{"key":"blockScenes.notification.properties.6.0","saveToPanel":false},"76":{"key":"blockScenes.notification.properties.6.76","saveToPanel":false}}},"barrier-safety-bearm-obstacle-status":{"key":"blockScenes.notification.properties.barrier-safety-bearm-obstacle-status","values":{"72":{"key":"blockScenes.notification.properties.6.72","saveToPanel":false}}}}},"9":{"eventValues":{},"key":"blockScenes.notification.properties.9","stateValues":{"hw-status":{"key":"blockScenes.notification.properties.hw-status","values":{"0":{"key":"blockScenes.notification.properties.9.0","saveToPanel":false},"3":{"key":"blockScenes.notification.properties.9.3","saveToPanel":false}}}}}},"useTemplate":true,"userDescription":""},"actions":{"close":0,"identify":0,"open":0,"reconfigure":0,"setIndicatorValue":1,"step":0,"stop":0},"created":1706275036,"modified":1706275237,"sortOrder":11}

**Comment by mkz212** [comment]
- Ok please add here screenshot of this device from Fibaro Panel (where field Role is)
- This is with positioning or only open close?

**Comment by mkz212** [comment]
Hmm.. But from what I see in the code it should be added. It is not visible in Homebridge? Or only not visible in Apple Home?

**Comment by stekki007** [comment]
![HCL](https://github.com/ilcato/homebridge-fibaro-home-center/assets/157816376/f0b2fa22-62b1-49a1-b417-3e65355bd156)

In HC3L it is working, not visible in Homebridge and not visible in Apple Home.  I use the admin account, my Fibaro plug is visible in Homebridge and also in Apple Home :)

**Comment by stekki007** [comment]
Is there anything I should try?  I really hope it can be added :s

**Comment by mkz212** [comment]
> Is there anything I should try? I really hope it can be added :s

As I wrote, from what I see in the code it should be displayed. I don't know why it doesn't show. If it were about the fact that it was displaying but as a bad type of device, I would have ideas, but that it did not show at all, I do not know.

**Comment by ilcato** [comment]
@mkz212 the case for ` 'com.fibaro.baseShutter'` simply doesn't match the properties of this device:

- controlType: 63 --> 1st and 3rd if escluded
- favoritePositionsNativeSupport is not present --> elseif excluded

**Comment by mkz212** [comment]
> @mkz212 the case for ` 'com.fibaro.baseShutter'` simply doesn't match the properties of this device (FibaroAccessory.ts):
> 
> * controlType: 63 --> 1st and 3rd if escluded
> * favoritePositionsNativeSupport is not present --> elseif excluded
> 
> Should we add controlType == 63 in the 1st if?

Look line 234 - it match all devices with type 'com.fibaro.baseShutter'

**Comment by ilcato** [comment]
> > @mkz212 the case for ` 'com.fibaro.baseShutter'` simply doesn't match the properties of this device (FibaroAccessory.ts):
> > 
> > * controlType: 63 --> 1st and 3rd if escluded
> > * favoritePositionsNativeSupport is not present --> elseif excluded
> > 
> > Should we add controlType == 63 in the 1st if?
> 
> Look line 234 - it match all devices with type 'com.fibaro.baseShutter' (If there was no more accurate match before)

The problem is the break in line 230

**Comment by mkz212** [comment]
Break in line 230 is not executed. Cause it is for: 

```
else if (this.device.type !== 'com.fibaro.baseShutter' ||
                   this.device.type === 'com.fibaro.baseShutter' && properties.favoritePositionsNativeSupport) {
```

**Comment by ilcato** [comment]
@stekki007 can you check into accessorycache if it is present?

**Comment by stekki007** [comment]
@ilcato as I am a noob, can you tell me where to look?  I am sorry :)

**Comment by mkz212** [comment]
> @ilcato as I am a noob, can you tell me where to look? I am sorry :)

Homebridge settings -> Remove one accessory from cache. But do not remove anything, only check if there is this accessory.

**Comment by stekki007** [comment]
@ilcato thanks, it is not in there, but the Wall Plug from my HC3L is!

**Comment by ilcato** [comment]
@stekki007 can you post the startup log?

**Comment by stekki007** [comment]
@ilcato

As you can see, the gate is not loading, only my WallPlug is being configured.  I really appreciate your effort, will donate if you guys find a solution for me :)

 [1/26/2024, 7:17:22 PM] [Homebridge UI] Homebridge restart request received
[1/26/2024, 7:17:22 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[1/26/2024, 7:17:22 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[1/26/2024, 7:17:22 PM] Got SIGTERM, shutting down Homebridge...
[1/26/2024, 7:17:22 PM] Got SIGTERM, shutting down child bridge process...
[1/26/2024, 7:17:27 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/26/2024, 7:17:32 PM] [HB Supervisor] Restarting Homebridge...
[1/26/2024, 7:17:32 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules -D --strict-plugin-resolution
[1/26/2024, 7:17:32 PM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 10389
[1/26/2024, 7:17:33 PM] Loaded config.json with 0 accessories and 4 platforms.
[1/26/2024, 7:17:33 PM] Loaded 6 cached accessories from cachedAccessories.
[1/26/2024, 7:17:33 PM] ---
[1/26/2024, 7:17:34 PM] Loaded plugin: homebridge-fibaro-hc3@1.1.14
[1/26/2024, 7:17:34 PM] Registering platform 'homebridge-fibaro-hc3.FibaroHC3'
[1/26/2024, 7:17:34 PM] ---
[1/26/2024, 7:17:34 PM] Loaded plugin: homebridge-govee@10.1.0
[1/26/2024, 7:17:34 PM] Registering platform 'homebridge-govee.Govee'
[1/26/2024, 7:17:34 PM] ---
[1/26/2024, 7:17:34 PM] Loaded plugin: homebridge-nest@4.6.9
[1/26/2024, 7:17:34 PM] Registering platform 'homebridge-nest.Nest'
[1/26/2024, 7:17:34 PM] ---
[1/26/2024, 7:17:34 PM] Loading 4 platforms...
[1/26/2024, 7:17:34 PM] [Nest] Initializing Nest platform...
[1/26/2024, 7:17:34 PM] [Govee] Initializing Govee platform...
[1/26/2024, 7:17:34 PM] [Govee] Initialising plugin v10.1.0 | System linux | Node v18.18.2 | HB v1.7.0 | HAPNodeJS v0.11.1...
[1/26/2024, 7:17:34 PM] [Govee] Config entry [apiKey] is unused and can be removed.
[1/26/2024, 7:17:34 PM] [Govee] Config entry [apiWhitelist] is unused and can be removed.
[1/26/2024, 7:17:34 PM] [Govee] Config entry [debug] is unused and can be removed.
[1/26/2024, 7:17:34 PM] [Govee] Config entry [lightDevices.FA:B7:CF:32:38:31:71:32.overrideLogging] is unused and can be removed.
[1/26/2024, 7:17:34 PM] [FibaroHC3] Initializing FibaroHC3 platform...
[1/26/2024, 7:17:34 PM] [FibaroHC3] Initializing child bridge 0E:38:78:87:E6:26
[1/26/2024, 7:17:34 PM] [Nest] Fetching Nest devices.
[1/26/2024, 7:17:34 PM] [Nest] Authenticating via access token.
[1/26/2024, 7:17:34 PM] [Govee] Plugin initialised. Setting up accessories....
[1/26/2024, 7:17:34 PM] Publishing bridge accessory (name: Homebridge AB79, publishInfo: {
  username: 'xxxxxxxx',
  port: 51225,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'eth0', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'ciao'
}).
Setup Payload:
X-HM://0023YRN2U0FRY
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxxxxxx   
    └────────────┘     
                       
[1/26/2024, 7:17:35 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge AB79) is running on port 51225.
[1/26/2024, 7:17:35 PM] [FibaroHC3] Launched child bridge with PID 10448
[1/26/2024, 7:17:36 PM] Registering platform 'homebridge-fibaro-hc3.FibaroHC3'
[1/26/2024, 7:17:36 PM] [FibaroHC3] Loaded homebridge-fibaro-hc3 v1.1.14 child bridge successfully
[1/26/2024, 7:17:36 PM] Loaded 1 cached accessories from cachedAccessories.0E387887E626.
[1/26/2024, 7:17:36 PM] [FibaroHC3] Error reading ca.cer:  Error: ENOENT: no such file or directory, open '/volume1/homebridge/ca.cer'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at new FibaroClient (/volume1/homebridge/node_modules/homebridge-fibaro-hc3/src/fibaro-api.ts:54:19)
    at new FibaroHC3 (/volume1/homebridge/node_modules/homebridge-fibaro-hc3/src/index.ts:139:23)
    at ChildBridgeFork.startBridge (/volume1/homebridge/node_modules/homebridge/src/childBridgeFork.ts:150:42) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/volume1/homebridge/ca.cer'
}
[1/26/2024, 7:17:36 PM] [FibaroHC3] Configured Accessory:  Wall Plug
[1/26/2024, 7:17:36 PM] Publishing bridge accessory (name: FibaroHC3, publishInfo: {
  username: '0E:38:78:87:E6:26',
  port: 40629,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'eth0', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'ciao'
}).
[1/26/2024, 7:17:36 PM] [FibaroHC3] didFinishLaunching. 
[1/26/2024, 7:17:36 PM] Homebridge v1.7.0 (HAP v0.11.1) (FibaroHC3) is running on port 40629.
[1/26/2024, 7:17:36 PM] [FibaroHC3] Loading accessories 
[1/26/2024, 7:17:36 PM] [FibaroHC3] Added/changed accessory:  Wall Plug
[1/26/2024, 7:17:37 PM] [Govee] [LAN] client enabled and found 0 device(s).
[1/26/2024, 7:17:37 PM] [FibaroHC3] Getting value from device:  21  parameter: On
[1/26/2024, 7:17:37 PM] [FibaroHC3] Getting value from device:  21  parameter: Outlet In Use
[1/26/2024, 7:17:37 PM] [Govee] [HTTP] client enabled and found 1 device(s).
[1/26/2024, 7:17:37 PM] [Govee] [AWS] client enabled.
[1/26/2024, 7:17:37 PM] [Govee] [BLE] disabling client as disabled in config.
[1/26/2024, 7:17:37 PM] [Govee] [Vloerlamp] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[1/26/2024, 7:17:37 PM] [Govee] [Vloerlamp] initialised with id [FA:B7:CF:32:38:31:71:32] [H6076].
[1/26/2024, 7:17:38 PM] [Nest] Authentication successful.
[1/26/2024, 7:17:39 PM] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[1/26/2024, 7:17:39 PM] [Govee] [Vloerlamp] current colour [2300K / 435M].
[1/26/2024, 7:17:47 PM] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC35170AQ1 structureId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068
[Living Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9
[1/26/2024, 7:17:47 PM] [Nest] Current temperature for Living Room Thermostat is: 20 °C / 68 °F
[1/26/2024, 7:17:47 PM] [Nest] Current heating/cooling state for Living Room Thermostat is: Heating
[1/26/2024, 7:17:47 PM] [Nest] Current humidity for Living Room Thermostat is: 53%
[1/26/2024, 7:17:47 PM] [Nest] Target temperature for Living Room Thermostat is: 20 °C / 68 °F
[1/26/2024, 7:17:47 PM] [Nest] Target heating/cooling state for Living Room Thermostat is: Heat
[1/26/2024, 7:17:47 PM] [Nest] Cooling threshold temperature for Living Room Thermostat is: 24 °C / 75.2 °F
[1/26/2024, 7:17:47 PM] [Nest] Heating threshold temperature for Living Room Thermostat is: 20 °C / 68 °F
[1/26/2024, 7:17:47 PM] [Nest] Online status for Living Room Thermostat is: true
[1/26/2024, 7:17:47 PM] [Nest] Sunlight Correction Enabled for Living Room Thermostat is: true
[1/26/2024, 7:17:47 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068 structureId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068
[1/26/2024, 7:17:47 PM] [Nest] Home Occupied for Home Occupied is: true
[1/26/2024, 7:17:47 PM] [Nest] initing protect "Upstairs": deviceId: 18B4300000B64397 structureId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068
[1/26/2024, 7:17:47 PM] [Nest] Online status (Smoke) for Upstairs is: online
[1/26/2024, 7:17:47 PM] [Nest] Online status (CO) for Upstairs is: online
[1/26/2024, 7:17:47 PM] [Nest] initing protect "Downstairs": deviceId: 18B4300000AF0933 structureId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068
[1/26/2024, 7:17:47 PM] [Nest] Online status (Smoke) for Downstairs is: online
[1/26/2024, 7:17:47 PM] [Nest] Online status (CO) for Downstairs is: online
[1/26/2024, 7:17:47 PM] [Nest] initing protect "Living Room": deviceId: 18B4300000AF1433 structureId: fde6c4c0-c194-11e8-9c1f-0e8a86a25068
[1/26/2024, 7:17:47 PM] [Nest] Online status (Smoke) for Living Room is: online
[1/26/2024, 7:17:47 PM] [Nest] Online status (CO) for Living Room is: online

**Comment by mkz212** [comment]
Loaded homebridge-fibaro-hc3 v1.1.14  ??

**Comment by stekki007** [comment]
@mkz212  what do you mean? :)

**Comment by ilcato** [comment]
@stekki007 it's a wrong plugin. How did you instyall it?

**Comment by stekki007** [comment]
@ilcato I just searched for HC3 in the plugin section of homebridge, what is the correct plugin?

**Comment by ilcato** [comment]
@stekki007 I consolidated all the different plugin into `homebridge-fibaro-home-center` it is compatible with all Fibaro and Yubii controller

**Comment by stekki007** [comment]
OK, so I uninstalled the wrong plugin and installed homebridge-fibaro-home-center.  This solved my problem, I see my gate in Homebridge and in Apple Home now.  I just tested and it works!  Thanks for the support guys!  This topic can be closed :)

**Comment by stekki007** [comment]
kk
