### ISSUE TITLE
about SecuritySystem error

### ISSUE THREAD

**Issue by baduxiyang** [ilcato/homebridge-fibaro-home-center#288]
[1/29/2024, 3:34:21 PM] [FibaroHC] Error fetching updates:  Error: Not Found
    at Request.callback (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:901:17)
    at fn (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1166:18)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  status: 404,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      text: '',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 12,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'GET',
      url: 'http://192.168.0.88/api/globalVariables/SecuritySystem',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      _lookup: undefined,
      throttle: [Throttle],
      serial: false,
      _maskedEnd: [Function (anonymous)],
      end: [Function (anonymous)],
      _maskedCallback: [Function (anonymous)],
      req: [ClientRequest],
      protocol: 'http:',
      host: '192.168.0.88',
      _endCalled: true,
      _callback: [Function: cleanup],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/globalVariables/SecuritySystem HTTP/1.1\r\n' +
        'Host: 192.168.0.88\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Authorization: Basic ********==\r\n' +
        'accept: json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/globalVariables/SecuritySystem',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.0.88',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    text: '',
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx',
      date: 'Mon, 29 Jan 2024 07:34:21 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'cache-control': 'no-cache, no-store'
    },
    header: {
      server: 'nginx',
      date: 'Mon, 29 Jan 2024 07:34:21 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'cache-control': 'no-cache, no-store'
    },
    statusCode: 404,
    status: 404,
    statusType: 4,
    info: false,
    ok: false,
    redirect: false,
    clientError: true,
    serverError: false,
    error: Error: cannot GET /api/globalVariables/SecuritySystem (404)
        at Response.toError (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:110:17)
        at Response._setStatusProperties (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/response-base.js:107:48)
        at new Response (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:41:8)
        at Request._emitResponse (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:953:20)
        at fn (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1166:38)
        at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/parsers/json.js:19:7)
        at IncomingMessage.emit (node:events:529:35)
        at endReadableNT (node:internal/streams/readable:1368:12)
        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
      status: 404,
      text: '',
      method: 'GET',
      path: '/api/globalVariables/SecuritySystem'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: true,
    unprocessableEntity: false,
    type: 'application/json',
    charset: 'UTF-8',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    _body: '',
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}

**Comment by ilcato** [comment]
Did you follow the guide in docs/security-system.md?
It seems that it is not able to find the required global variables.

**Comment by baduxiyang** [comment]
@ilcato 
The global variables are correct, but when I select any option in homekit, there is no way to take effect. However, after running the scenario, the options in homekit will change.

**Comment by ilcato** [comment]
@baduxiyang is the user accessing Fibaro Home Center an admin user? In order to set Global Variables this is a requirement.

**Comment by baduxiyang** [comment]
@ilcato yes,i set the admin and password

and i test Doorbell :
Can it be two or more Doorbell device IDs

**Comment by ilcato** [comment]
@baduxiyang can you try 1.7.4-beta.0 and post the new log with the same conditions as before?

**Comment by baduxiyang** [comment]
ok i will try! Thank you!

**Comment by baduxiyang** [comment]
@ilcato update slowly:
USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-fibaro-home-center@1.7.4-beta.0

[..................] \ idealTree:homebridge: sill idealTree buildDeps

**Comment by baduxiyang** [comment]
@ilcato 
`[1/30/2024, 5:14:10 PM] [FibaroHC] Loading accessories
[1/30/2024, 5:14:10 PM] [FibaroHC] Adding new accessory: FibaroSecuritySystem
[1/30/2024, 5:14:10 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:12 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:14 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:16 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:18 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:20 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:23 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:28 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:30 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:32 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:34 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:36 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:38 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:40 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:44 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:49 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:51 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:53 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:14:55 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:01 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:05 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:07 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:09 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:11 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:13 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:16 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:20 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:22 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:24 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:26 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:28 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:30 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:32 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:37 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:44 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:48 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:52 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:54 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}
[1/30/2024, 5:15:56 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'StayArmed',
  readOnly: false,
  isEnum: false,
  enumValues: [],
  created: 1706513670,
  modified: 1706514466
}`

**Comment by baduxiyang** [comment]
Uploading Video_24-01-30_17-27-30.mp4…

**Comment by baduxiyang** [comment]
https://github.com/ilcato/homebridge-fibaro-home-center/assets/53244835/a61d5ae1-364e-482d-914b-10262603a979

**Comment by ilcato** [comment]
@baduxiyang are the scenes flagged with the `Allow to run when alarm breached` ?

**Comment by baduxiyang** [comment]
@ilcato yes! it Allow to run when alarm breached

**Comment by ilcato** [comment]
@baduxiyang, can you show me the definition of the global variable?

**Comment by baduxiyang** [comment]
![屏幕截图 2024-01-31 142634](https://github.com/ilcato/homebridge-fibaro-home-center/assets/53244835/cbcf717b-c76e-4898-b53d-355b1b05a98d)

**Comment by baduxiyang** [comment]
`[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:14:48 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:14:48 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:14:48 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:14:48 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:14:48 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:14:52 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:14:57 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:01 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:03 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:08 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:13 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:19 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:21 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:23 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:25 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:29 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:35 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:15:35 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:15:35 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:15:35 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:15:35 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:15:35 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:15:38 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:15:38 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:15:38 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:15:38 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室空调 [4]: getting Current Heating Cooling State
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室空调 [4]: getting Target Heating Cooling State
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室空调 [4]: getting Current Temperature
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室空调 [4]: getting Target Temperature
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室空调 [4]: getting Temperature Display Units
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室地暖 [5]: getting Current Heating Cooling State
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室地暖 [5]: getting Target Heating Cooling State
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室地暖 [5]: getting Current Temperature
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室地暖 [5]: getting Target Temperature
[2/1/2024, 9:15:40 PM] [FibaroHC] 办公室地暖 [5]: getting Temperature Display Units
[2/1/2024, 9:15:40 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Current State
[2/1/2024, 9:15:40 PM] [FibaroHC] FibaroSecuritySystem [0]: getting Security System Target State
[2/1/2024, 9:15:40 PM] [FibaroHC] securitySystemStatus:  {
  name: 'SecuritySystem',
  value: 'Disarmed',
  readOnly: false,
  isEnum: true,
  enumValues: [
    'AlarmTriggered',
    'AwayArmed',
    'Disarmed',
    'NightArmed',
    'StayArmed'
  ],
  created: 1706792115,
  modified: 1706792294
}
[2/1/2024, 9:15:45 PM] [FibaroHC] securitySystemStatus:  {
[2/1/2024, 9:15:51 PM] [FibaroHC] securitySystemStatus:  {`

**Comment by baduxiyang** [comment]
![屏幕截图 2024-02-01 211657](https://github.com/ilcato/homebridge-fibaro-home-center/assets/53244835/6ff7f040-9246-4851-93d9-60870bfac424)

**Comment by baduxiyang** [comment]
@ilcato FibaroSecuritySystem [0]: getting Security System Current State
Is it just reading variables? Can global variables be set in Homebridge？

**Comment by ilcato** [comment]
> @ilcato FibaroSecuritySystem [0]: getting Security System Current State Is it just reading variables? Can global variables be set in Homebridge？

I do not understand this questions.
Is it working now?
