### ISSUE TITLE
Plugin dead after update to 1.7.4beta2

### ISSUE THREAD

**Issue by rafalantas** [ilcato/homebridge-fibaro-home-center#311]
Hi,

I clicked update to 1.7.4beta2 and it is throwing critical error and crashing plugin.

[FibaroHC] Launched child bridge with PID 52379
[21/02/2024, 23:09:03] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[21/02/2024, 23:09:03] [FibaroHC] Loaded homebridge-fibaro-home-center v1.7.4-beta.2 child bridge successfully
[21/02/2024, 23:09:03] Loaded 1 cached accessories from cachedAccessories.0E4D88ACA9BB.
[21/02/2024, 23:09:03] Homebridge v1.7.0 (HAP v0.11.1) (FibaroHC) is running on port 52045.
[21/02/2024, 23:09:03] [FibaroHC] Loading accessories
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit
(node:52379) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit

/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527
    callback(undefined, characteristic.value);
    ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FibaroAccessory.getCharacteristicValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527:5)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:498:14)
    at StatusLowBattery.emit (node:events:530:35)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
[21/02/2024, 23:09:06] [FibaroHC] Child bridge process ended
[21/02/2024, 23:09:06] [FibaroHC] Process Ended. Code: 1, Signal: null
[21/02/2024, 23:09:13] [FibaroHC] Restarting Process...
[21/02/2024, 23:09:13] [FibaroHC] Launched child bridge with PID 52585

reverted back to 1.7.3 since I cannot see beta1 which was fine :)
reverting removed all my device and added them once again

thanks,
Rafał

**Comment by mkz212** [comment]
@rafalantas 

Unfortunately, the last 20 versions are displayed in Homebridge UI, but only one last beta. So you can see, for example, the public version from 5 years ago, but you can not see the beta version from yesterday. I have already submitted an fix to this.

As for the error, I see that the change between beta 1 and beta 2 is quite small and should not cause a problem. Maybe it's through the cache in Homebridge? Have you tried to remove the troublesome device from the cache after installing beta 2 (in the Homebridge settings)?

**Comment by mkz212** [comment]
@rafalantas 

You can install beta 1, go to Homebridge terminal and type:

```
npm install -g fibaro-home-center@1.7.4-beta.1
```

**Comment by rafalantas** [comment]
ok i made some test. updated from 1.7.3 to beta2 and it removing accessories and adding them back and crashing. I tried to remove all accessories and it is crashing too..

**Comment by ilcato** [comment]
@rafalantas,

- are you on hc2?
- do you have climate/heating zones?
- can you post the log of after the clean install?

**Comment by rafalantas** [comment]
Hi @ilcato 

I have HC3 and I do use heating zones 


[22/02/2024, 08:51:46] [FibaroHC] Launched child bridge with PID 86319
[22/02/2024, 08:51:47] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[22/02/2024, 08:51:47] [FibaroHC] Loaded homebridge-fibaro-home-center v1.7.4-beta.2 child bridge successfully
[22/02/2024, 08:51:47] Loaded 0 cached accessories from cachedAccessories.0E4D88ACA9BB.
[22/02/2024, 08:51:47] Homebridge v1.7.0 (HAP v0.11.1) (FibaroHC) is running on port 52045.
[22/02/2024, 08:51:47] [FibaroHC] Adding new accessory: Biuro
[22/02/2024, 08:51:47] [FibaroHC] Loading accessories
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit
(node:86319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit

/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527
    callback(undefined, characteristic.value);
    ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FibaroAccessory.getCharacteristicValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527:5)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:498:14)
    at StatusLowBattery.emit (node:events:530:35)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
[22/02/2024, 08:51:48] [FibaroHC] Child bridge process ended
[22/02/2024, 08:51:48] [FibaroHC] Process Ended. Code: 1, Signal: null
[22/02/2024, 08:51:55] [FibaroHC] Restarting Process...
[22/02/2024, 08:51:56] [FibaroHC] Launched child bridge with PID 86448
[22/02/2024, 08:51:56] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[22/02/2024, 08:51:56] [FibaroHC] Loaded homebridge-fibaro-home-center v1.7.4-beta.2 child bridge successfully
[22/02/2024, 08:51:56] Loaded 1 cached accessories from cachedAccessories.0E4D88ACA9BB.
[22/02/2024, 08:51:56] Homebridge v1.7.0 (HAP v0.11.1) (FibaroHC) is running on port 52045.
[22/02/2024, 08:51:57] [FibaroHC] Loading accessories
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [BatteryLevel]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [ChargingState]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit
(node:86448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get listeners added to [StatusLowBattery]. Use emitter.setMaxListeners() to increase limit

/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527
    callback(undefined, characteristic.value);
    ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FibaroAccessory.getCharacteristicValue (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:527:5)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:498:14)
    at StatusLowBattery.emit (node:events:530:35)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at StatusLowBattery.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
[22/02/2024, 08:52:05] [FibaroHC] Child bridge process ended
[22/02/2024, 08:52:05] [FibaroHC] Process Ended. Code: 1, Signal: null
[22/02/2024, 08:52:12] [FibaroHC] Restarting Process...




After clean install I can see that it cached just one device Biuro. Is it getting heating zone first ?

**Comment by ilcato** [comment]
@rafalantas try beta 3
