### ISSUE TITLE
Fibaro RGBW error

### ISSUE THREAD

**Issue by rainerse** [ilcato/homebridge-fibaro-home-center#502]
### Product (manufacturer, model)

fibaro RGBW, FGRGBW-442

### As what should be displayed?

dimmer

### API response for this device

```code
{
    "id": 292,
    "name": "vann valgus",
    "roomID": 230,
    "type": "com.fibaro.multilevelSwitch",
    "baseType": "com.fibaro.binarySwitch",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 152,
    "remoteGatewayId": 0,
    "interfaces": [
        "RGBWOutput",
        "deviceGrouping",
        "levelChange",
        "light",
        "zwave"
    ],
    "properties": {
        "parameters": [
            {
                "id": 1,
                "lastReportedValue": 255,
                "lastSetValue": 255,
                "size": 1,
                "value": 255
            },
            {
                "id": 8,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 9,
                "lastReportedValue": 1,
                "lastSetValue": 1,
                "size": 1,
                "value": 1
            },
            {
                "id": 10,
                "lastReportedValue": 10,
                "lastSetValue": 10,
                "size": 2,
                "value": 10
            },
            {
                "id": 12,
                "lastReportedValue": 159,
                "lastSetValue": 159,
                "size": 1,
                "value": 159
            },
            {
                "id": 13,
                "lastReportedValue": 2,
                "lastSetValue": 2,
                "size": 1,
                "value": 2
            },
            {
                "id": 15,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 16,
                "lastReportedValue": 1,
                "lastSetValue": 1,
                "size": 1,
                "value": 1
            },
            {
                "id": 30,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 38,
                "lastReportedValue": 10,
                "lastSetValue": 10,
                "size": 1,
                "value": 10
            },
            {
                "id": 39,
                "lastReportedValue": 600,
                "lastSetValue": 600,
                "size": 2,
                "value": 600
            },
            {
                "id": 44,
                "lastReportedValue": 30,
                "lastSetValue": 30,
                "size": 2,
                "value": 30
            },
            {
                "id": 45,
                "lastReportedValue": 10,
                "lastSetValue": 10,
                "size": 1,
                "value": 10
            },
            {
                "id": 49,
                "lastReportedValue": 1,
                "lastSetValue": 1,
                "size": 1,
                "value": 1
            },
            {
                "id": 71,
                "lastReportedValue": 1,
                "lastSetValue": 1,
                "size": 1,
                "value": 1
            },
            {
                "id": 73,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 6,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 14,
                "lastReportedValue": 39321,
                "lastSetValue": 39321,
                "size": 2,
                "value": 39321
            },
            {
                "id": 42,
                "lastReportedValue": 0,
                "lastSetValue": 0,
                "size": 1,
                "value": 0
            },
            {
                "id": 11,
                "lastReportedValue": 67,
                "lastSetValue": 67,
                "size": 1,
                "value": 67
            },
            {
                "id": 43,
                "lastReportedValue": 5,
                "lastSetValue": 5,
                "size": 1,
                "value": 5
            }
        ],
        "pollingTimeSec": 0,
        "zwaveCompany": "Fibargroup",
        "zwaveInfo": "3,3,67",
        "zwaveVersion": "27.27",
        "buttonType": "0",
        "categories": "[\"lights\"]",
        "configured": true,
        "dead": "false",
        "deadReason": "",
        "deviceControlType": "23",
        "deviceGroup": "[]",
        "deviceGroupMaster": "0",
        "deviceIcon": "15",
        "emailNotificationID": "0",
        "emailNotificationType": "0",
        "endPointId": "3",
        "isLight": "true",
        "log": "",
        "logTemp": "",
        "manufacturer": "",
        "markAsDead": "true",
        "model": "",
        "nodeId": "16",
        "parametersTemplate": "851",
        "productInfo": "1,15,9,0,16,0,27,27",
        "pushNotificationID": "0",
        "pushNotificationType": "0",
        "remoteGatewayId": "0",
        "saveLogs": "true",
        "serialNumber": "",
        "smsNotificationID": "0",
        "smsNotificationType": "0",
        "useTemplate": "true",
        "userDescription": "",
        "value": "0"
    },
    "actions": {
        "reconfigure": 0,
        "setValue": 1,
        "startLevelDecrease": 0,
        "startLevelIncrease": 0,
        "stopLevelChange": 0,
        "turnOff": 0,
        "turnOn": 0
    },
    "created": 1728738670,
    "modified": 1728738670,
    "sortOrder": 156
}
```

### Additional info

[10/12/2024, 4:40:17 PM] [FibaroHC] Error getting data from Home Center:  Error: Unsupported device role for multilevel sensor: undefined
    at multilevelSensor (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/deviceAuto.ts:237:13)
    at FibaroAccessory.configureAccessoryFromType (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:392:43)
    at new FibaroAccessory (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:54:12)
    at FibaroHC.addAccessory (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:303:18)
    at /volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:227:14
    at Array.map (<anonymous>)
    at FibaroHC.LoadAccessories (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:210:13)
    at FibaroHC.login (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:177:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ilcato** [comment]
@rainerse thank you for your report but it's not clear to me.
The device you mention is an RGBW device and should be reported with a type with its name or a generic 'com.fibaro.colorController'. Instead it says it's an 'com.fibaro.multilevelSwitch' that indeed should be a dimmer.
Are you sure that the json data correspond to the right device?

Additionally, the log you attached is relative to a 'multilevelSensor'. 

Can you clarify?

**Comment by ilcato** [comment]
@rainerse can you test 3.1.1-beta.4 ?

**Comment by ilcato** [comment]
@rainerse this is fixed by 3.1.1

**Comment by rainerse** [comment]
Tested 3.2.0 beta 0. Now the plugin working. And the multilever switch is as a dimmer

Thank you

**Comment by ilcato** [comment]
Good. Please close the issue.
