### ISSUE TITLE
Plug encounter 'Cannot add a Service with the same UUID' error

### ISSUE THREAD

**Issue by hofoongwai** [ilcato/homebridge-fibaro-home-center#522]
### Description

encounter 'Cannot add a Service with the same UUID' after upgrading from version 3.0 of the plugin.  Need to downgrade for HomeKit to control devices

### Logs

```code
[22/10/2024, 14:02:50] [FibaroHC] Error getting data from Home Center:  Error: Cannot add a Service with the same UUID '00000043-0000-1000-8000-0026BB765291' and subtype '23----' as another Service in this Accessory.
    at Accessory.addService (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:561:17)
    at PlatformAccessory.addService (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:99:41)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:98:28
    at Array.forEach (<anonymous>)
    at new FibaroAccessory (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:94:31)
    at FibaroHC.addAccessory (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:318:18)
    at /var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:253:14
    at Array.map (<anonymous>)
    at FibaroHC.processDevices (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:236:18)
    at FibaroHC.login (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:153:12)
```

### Plugin config

```JSON
{
    "name": "FibaroHC",
    "url": "192.168.3.191",
    "username": "XXXXXXXX",
    "password": "XXXXXXXX",
    "pollerperiod": 3,
    "markDeadDevices": false,
    "thermostattimeout": 7200,
    "thermostatmaxtemperature": 100,
    "securitysystem": "disabled",
    "addRoomNameToDeviceName": "enabledBefore",
    "logsLevel": 2,
    "_bridge": {
        "username": "0E:A7:1A:39:4A:16",
        "port": 56913
    },
    "platform": "FibaroHC"
}
```

### Plugin version

3.1.1

### Fibaro HC / Yubii Home type and firmware

FIbaro Home Center 3, v5.183.59

**Comment by ilcato** [comment]
@hofoongwai Thank you for the report. Can you tell me the type of the device 23?

**Comment by ilcato** [comment]
@hofoongwai can you test please 3.2.0-beta.4 ?

**Comment by hofoongwai** [comment]
> @hofoongwai Thank you for the report. Can you tell me the type of the device 23? Another question: did you rename the device 23?

How to tell device 23?  Based on Fibaro device ID?  If based on Fibaro device ID, it is a z-wave controlled light switch

**Comment by ilcato** [comment]
@hofoongwai can you test please 3.2.0-beta.4 ?

**Comment by hofoongwai** [comment]
> @hofoongwai can you test please 3.2.0-beta.4 ?

Yes! 3.2.0-beta.4 works!  The error is no longer there and controls are working

**Comment by ilcato** [comment]
Ok, I will release 3.2.0 in a few moments.
Please close the issue.
