### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by SIKiwi** [ilcato/homebridge-fibaro-home-center#66]
Hi 
I have updated to homebridge Fibaro Home Center plugin and am getting the error below.
HC2 v4.62
Virtual Devices are not seen in homekit
Any ideas?
Thanks

(node:3296) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:6:13
    at FibaroAccessory.getCharacteristicValue (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge-fibaro-home-center\src\fibaroAccessory.ts:434:9)
    at On.<anonymous> (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge-fibaro-home-center\src\fibaroAccessory.ts:330:16)
    at On.emit (events.js:412:35)
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at On.<anonymous> (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1542:12)
    at step (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:117:75
(node:3296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:3296) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:6:13
    at FibaroAccessory.getCharacteristicValue (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge-fibaro-home-center\src\fibaroAccessory.ts:434:9)
    at On.<anonymous> (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge-fibaro-home-center\src\fibaroAccessory.ts:330:16)
    at On.emit (events.js:412:35)
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at On.<anonymous> (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1542:12)
    at step (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at C:\Users\OEM\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:117:75
(node:3296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

**Comment by ilcato** [comment]
Virtual device are no more supported.
