### ISSUE TITLE
Beta update available as “Latest version”

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#82]
Hi ilcato.

Homebridge tells me there is an update for your plug-in, but it points out as 1.2.5-Beta-0. Moreover, not the 0 nor the beta-2 will correcty install. I cannot report here the problem but it seems there are compatibility issues with node.js and npm (I have 16.13.1 and 8.1.2).

Thanks

**Comment by ilcato** [comment]
@redeemer666,  1.2.5-Beta-0 shouldn't be no more present.
What kind of error do you see in the beta? Can you post it here?

**Comment by redeemer666** [comment]
Hi @ilcato 
Still seeing as available as update.

This is the error I got after installing it

[10/01/2022, 15:56:47] [FibaroHC] Initializing FibaroHC platform...
[10/01/2022, 15:56:48] TypeError: Cannot read properties of undefined (reading 'indexOf')
    at new FibaroClient (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/fibaro-api.ts:52:27)
    at new FibaroHC (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:76:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[10/01/2022, 15:56:48] Got SIGTERM, shutting down Homebridge...

Cannot report the error during installation though

**Comment by redeemer666** [comment]
Hi @ilcato 

Installed 1.2.6. Still getting error attached during installation, but this time it’s working fine.
<img width="798" alt="Immagine PNG" src="https://user-images.githubusercontent.com/9434736/148808017-ddbbcae9-fa87-4297-b7fe-51d7482c0560.png">
