### ISSUE TITLE
Keeps restarting, throwing error

### ISSUE THREAD

**Issue by amatt09** [ilcato/homebridge-fibaro-home-center#98]
after installation homebridge beings to run, it comes up with the following error. Does anyone know how to resolve these errors? have have reinstalled homebridge, deleted all the folders, upgraded npm and node JS. 

[4/25/2022, 5:21:28 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at FibaroAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:440:9)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:331:16)
    at CurrentTemperature.emit (node:events:539:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
[4/25/2022, 5:21:29 PM] Got SIGTERM, shutting down Homebridge...
[4/25/2022, 5:21:34 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by Berti321** [comment]
Hi i have the same Problem.

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at FibaroAccessory.getCharacteristicValue (/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:440:9)
    at CurrentHeatingCoolingState.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:331:16)
    at CurrentHeatingCoolingState.emit (node:events:538:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at CurrentHeatingCoolingState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
[5/6/2022, 1:01:04 PM] Error: This callback function has already been called by someone else;

**Comment by KJTamas** [comment]
Hi, same here. (i not copied the log, because that is same too) Anybody have a solution?

**Comment by amatt09** [comment]
I think I have found the issue, I removed accessories from the user access in home center. I started to add them back by room and found that my z-wave thermostat was causing the issue for some reason. Not sure what changed recently but that is what I have narrowed it down to.

**Comment by KJTamas** [comment]
I think i found the root cause. I have a motion sensor in kitchen. One z-wave device looks like one motion sensor, one teperature sensor, one light sensor etc. Accidentally two devices (motion sensor and temperature sensor) has the identically same name. :( I changed the temperature sensor name, and heureka, everiting works fine!

**Comment by Berti321** [comment]
I have checked all devices but I have not found a duplicate name

**Comment by Berti321** [comment]
I have disabled all devices and still the error is displayed.

And only the ID 1 & ID 2 remained over 

![4](https://user-images.githubusercontent.com/85880882/168904929-e2ddb05b-d991-495b-bc93-294a2e9acf80.PNG)
![1](https://user-images.githubusercontent.com/85880882/168904933-eebeabeb-92cb-4085-82b1-c043a870a0c7.PNG)

**Comment by KJTamas** [comment]
Which user use to connect HC? Admin or created a new user? What does it mean "disabled"?

**Comment by Berti321** [comment]
I have created a new user: homebridge
I have disabled the devices for testing with the user, I made a picture of it


![1](https://user-images.githubusercontent.com/85880882/168975029-403c3f65-94fd-4a8a-a0ae-065ebacd89e4.PNG)
![2](https://user-images.githubusercontent.com/85880882/168975032-c477f499-9245-4e7e-8050-9fbf33be2e2c.PNG)
![3](https://user-images.githubusercontent.com/85880882/168975034-23b3a067-94dd-49ad-8b3b-d6260f208ff6.PNG)

**Comment by KJTamas** [comment]
Have you tried clear the cache?

**Comment by Berti321** [comment]
Thanks for your help, I could not clear the cache, there was always something in it until I noticed that the error was generated by the header plans. I disabled the user's access to the plans and the error is gone.
![22](https://user-images.githubusercontent.com/85880882/169394248-81bb820c-938f-4be2-8c63-a8d42e56817e.PNG)

**Comment by Berti321** [comment]
You can leave the plans on but you have to give each plan its own name. =) =
![223](https://user-images.githubusercontent.com/85880882/169396968-80c656ea-bd9b-40b4-9eb7-64a5a3d74f02.PNG)
)

**Comment by ilcato** [comment]
@Berti321, sorry for the late response.
Yes a thermostat is created for every temperature zone and they must have a unique name.

**Comment by ilcato** [comment]
@amatt09, @KJTamas were you able to fix the problem ?
The clear cache accessories option and having a unique name for all the devices **within a single room** should fix the problem.
As @Berti321 found, also the temperature zone must have a unique name.

**Comment by KJTamas** [comment]
@ilcato I don't cleared the cache, because maybe lost of automations in HK, only i gave an unique name every devices. This solved the problem. For me.. :)

**Comment by ilcato** [comment]
@KJTamas, ok. Remember that with the homebridge UI you can selectively delete any single accessory from the cache.

**Comment by KJTamas** [comment]
> @KJTamas, ok. Remember that with the homebridge UI you can selectively delete any single accessory from the cache.

Yes, i know it, but earlier when i cleared the all cached devices, i lost all automations where the Fibaro was the trigger. 🥺 So carful with the clearing cache. 🫡

**Comment by crescentit** [comment]
This is happening for me as well. I have tried to remove all duplicates from HC3. :(
